#!/bin/bash

output_file=./cf-services.json
rm -v ./cf-services.json

source ./cf_parameters

jq '{id: "services", groups: [{id: "/services/jobs", apps: .}]}' --slurp ./services/*.json > ${output_file}
sed -i "s/\"MESOS_SLAVE_COUNT_PLACEHOLDER\"/$MESOS_SLAVE_COUNT/g" ${output_file}
sed -i "s/HOST_IP_PLACEHOLDER/$HOST_IP/g" ${output_file}
sed -i "s/HOST_URL_PLACEHOLDER/$HOST_URL/g" ${output_file}
