#!/usr/bin/env bash

# Enable or disable Diego backend
# Default: false
DIEGO_ENABLED=true
# Username of the Cloud Foundry admin user.
# Default: admin
CF_ADMIN_USER=admin
# Password of the Cloud Foundry admin user
# Default: c1oudc0w
CF_ADMIN_PASSWORD=c1oudc0w123
# Domain for your Cloud Foundry and apps. You may find
# xip.io useful if you don't have your own domain name,
# e.g. 192.168.0.1.xip.io
CF_DOMAIN=127.0.0.1.xip.io
# Email address to contact for support for your Cloud Foundry
CF_SUPPORT_ADDRESS=cf_api_support_address@whateveryouwant.email
# -OPTIONAL- URL or IP of an external syslog drain for your Cloud Foundry
CF_SYSLOG_DRAIN_ADDRESS=
# -OPTIONAL- Port of your external syslog drain
CF_SYSLOG_DRAIN_PORT=
# -OPTIONAL- Transport for your external syslog drain. Can be tcp, udp or relp
CF_SYSLOG_DRAIN_TRANSPORT=


declare -A kv_array
kv_array=(
  ["/cf/admin_password"]="${CF_ADMIN_PASSWORD:-c1oudc0w}"
  ["/cf/admin_user"]="${CF_ADMIN_USER:-admin}"
  ["/cf/domain"]="${CF_DOMAIN}"
  ["/cf/jobs/diego/enabled"]="${DIEGO_ENABLED:-false}"
  ["/cf/support_address"]="${CF_SUPPORT_ADDRESS}"
  ["/cf/ssl_pem"]="$(cat ./ssl.pem)"
  ["/cf/syslog_drain/address"]="${CF_SYSLOG_DRAIN_ADDRESS}"
  ["/cf/syslog_drain/port"]="${CF_SYSLOG_DRAIN_PORT}"
  ["/cf/syslog_drain/transport"]="${CF_SYSLOG_DRAIN_TRANSPORT}"
)
