{{ if eq (SYSLOG-DRAIN-TRANSPORT-PLACEHOLDER-f622194a) "relp" }}
$ModLoad omrelp
*.* :omrelp:SYSLOG-DRAIN-ADDRESS-PLACEHOLDER-f622194a:SYSLOG-DRAIN-PORT-PLACEHOLDER-f622194a;CfLogTemplate
{{ else if eq (SYSLOG-DRAIN-TRANSPORT-PLACEHOLDER-f622194a) "udp" }}
*.* @SYSLOG-DRAIN-ADDRESS-PLACEHOLDER-f622194a:SYSLOG-DRAIN-PORT-PLACEHOLDER-f622194a;CfLogTemplate
{{ else if eq (SYSLOG-DRAIN-TRANSPORT-PLACEHOLDER-f622194a) "tcp" }}
*.* @@SYSLOG-DRAIN-ADDRESS-PLACEHOLDER-f622194a:SYSLOG-DRAIN-PORT-PLACEHOLDER-f622194a;CfLogTemplate
{{ else }}
#only RELP, UDP, and TCP are supported
{{ end }}
